@baseTheme = dark

@background = #282828
@foreground = #ebdbb2
@header = #3c3836
@selection = #504945
@accent = #fe8019

Panel.background = @background
Panel.foreground = @foreground

TitlePane.background = @background
TitlePane.foreground = @foreground

MenuBar.background = @background
MenuBar.foreground = @foreground

Menu.background = @background
Menu.foreground = @foreground
Menu.selectionBackground = #007aff
Menu.selectionForeground = #ffffff
Menu.selectionArc = 6
Menu.selectionInsets = 2,5,2,5

MenuItem.background = @background
MenuItem.foreground = @foreground
MenuItem.selectionBackground = #007aff
MenuItem.selectionForeground = #ffffff
MenuItem.selectionArc = 6
MenuItem.selectionInsets = 2,5,2,5

TabbedPane.background = @background
TabbedPane.selectedBackground = @header
TabbedPane.foreground = @foreground

List.background = @background
List.foreground = @foreground
List.selectionBackground = @selection

TextField.background = @background
TextField.foreground = @foreground

PasswordField.background = @background
PasswordField.foreground = @foreground

ComboBox.background = @background
ComboBox.foreground = @foreground

Button.background = @header
Button.foreground = @foreground

Component.focusColor = @accent
