@background = #fbf1c7
@foreground = #3c3836
@header = #ebdbb2
@selection = #d5c4a1

Panel.background = @background
Panel.foreground = @foreground

TitlePane.background = @background
TitlePane.foreground = @foreground

MenuBar.background = @background
MenuBar.foreground = @foreground

Menu.background = @background
Menu.foreground = @foreground

MenuItem.background = @background
MenuItem.foreground = @foreground

TabbedPane.background = @background
TabbedPane.selectedBackground = @header
TabbedPane.foreground = @foreground
TabbedPane.selectedForeground = @foreground

List.background = @background
List.foreground = @foreground
List.selectionBackground = @selection
List.selectionForeground = @foreground

TextField.background = @background
TextField.foreground = @foreground

PasswordField.background = @background
PasswordField.foreground = @foreground

ComboBox.background = @background
ComboBox.foreground = @foreground

Button.background = @header
Button.foreground = @foreground

ToolBar.background = @background

ScrollBar.track = @background
