export const getXtermTheme = (theme: string) => {
    switch (theme) {
        case 'Dark':
            return {
                background: '#0F172A',
                foreground: '#E2E8F0',
                cursor: '#E2E8F0',
                selectionBackground: 'rgba(99, 102, 241, 0.3)',
                black: '#0F172A',
                red: '#ef4444',
                green: '#10b981',
                yellow: '#fbbf24',
                blue: '#6366f1',
                magenta: '#d946ef',
                cyan: '#06b6d4',
                white: '#E2E8F0',
                brightBlack: '#94A3B8',
                brightRed: '#f87171',
                brightGreen: '#34d399',
                brightYellow: '#fbbf24',
                brightBlue: '#818cf8',
                brightMagenta: '#f0abfc',
                brightCyan: '#22d3ee',
                brightWhite: '#F8FAFC',
            };
        case 'Gruvbox Light':
            return {
                background: '#fbf1c7',
                foreground: '#282828',
                cursor: '#3c3836',
                selectionBackground: '#d5c4a1',
                black: '#282828',
                red: '#cc241d',
                green: '#98971a',
                yellow: '#d79921',
                blue: '#458588',
                magenta: '#b16286',
                cyan: '#427b58',
                white: '#7c6f64',
                brightBlack: '#928374',
                brightRed: '#9d0006',
                brightGreen: '#79740e',
                brightYellow: '#b57614',
                brightBlue: '#076678',
                brightMagenta: '#8f3f71',
                brightCyan: '#427b58',
                brightWhite: '#3c3836',
            };
        case 'Gruvbox Dark':
            return {
                background: '#282828',
                foreground: '#ebdbb2',
                cursor: '#ebdbb2',
                selectionBackground: '#504945',
                black: '#282828',
                red: '#cc241d',
                green: '#98971a',
                yellow: '#d79921',
                blue: '#458588',
                magenta: '#b16286',
                cyan: '#689d6a',
                white: '#a89984',
                brightBlack: '#928374',
                brightRed: '#fb4934',
                brightGreen: '#b8bb26',
                brightYellow: '#fabd2f',
                brightBlue: '#83a598',
                brightMagenta: '#d3869b',
                brightCyan: '#8ec07c',
                brightWhite: '#ebdbb2',
            };
        case 'Windows Terminal':
            return {
                background: '#0C0C0C',
                foreground: '#CCCCCC',
                cursor: '#FFFFFF',
                selectionBackground: 'rgba(255, 255, 255, 0.3)',
                black: '#0C0C0C',
                red: '#C50F1F',
                green: '#13A10E',
                yellow: '#C19C00',
                blue: '#0037DA',
                magenta: '#881798',
                cyan: '#3A96DD',
                white: '#CCCCCC',
                brightBlack: '#767676',
                brightRed: '#E74856',
                brightGreen: '#16C60C',
                brightYellow: '#F9F1A5',
                brightBlue: '#3B78FF',
                brightMagenta: '#B4009E',
                brightCyan: '#61D6D6',
                brightWhite: '#F2F2F2',
            };
        case 'Light':
        default:
            return {
                background: '#F8FAFC',
                foreground: '#0F172A',
                cursor: '#0F172A',
                selectionBackground: 'rgba(79, 70, 229, 0.1)',
                black: '#0F172A',
                red: '#ef4444',
                green: '#10b981',
                yellow: '#f59e0b',
                blue: '#4f46e5',
                magenta: '#d946ef',
                cyan: '#06b6d4',
                white: '#64748B',
                brightBlack: '#94A3B8',
                brightRed: '#f87171',
                brightGreen: '#34d399',
                brightYellow: '#fbbf24',
                brightBlue: '#6366f1',
                brightMagenta: '#f0abfc',
                brightCyan: '#22d3ee',
                brightWhite: '#0F172A',
            };
    }
};
